bugfix onboardWholesale & create api get farmer
hasimy-as/temen-tani-services pull request #6
Opened 2021-10-05 16:24 UTC by mad-af

2021-10-05 16:30 UTC, nadiahna approved these changes

2021-10-06 01:03 UTC, hasimy-as requested changes
Btw tolong mergenya ke branch develop aja, sama petiknya diganti petik satu biar ngga error di eslintnya @mad-af

2021-10-06 01:03 UTC, hasimy-as commented on server/src/server.js
> +  // await observer.init();
Ini jangan di comment fa @mad-af

2021-10-06 02:15 UTC, hasimy-as approved these changes

2021-10-06 02:15 UTC, merged